### ISSUE TITLE
Semantic version

### ISSUE THREAD

**Issue by mbaxter91288** [matejlatin/Gutenberg#15]
Hi,

Just tried installing Gutenberg via NPM and it's coming up with an error that version 0.1 is invalid. Upon some searching it seems it needs semantic version numbers.

[http://stackoverflow.com/questions/16887993/npm-why-is-a-version-0-1-invalid#answer-16888025](npm: Why is a version “0.1” invalid?)

It looks like updating the pakage.json file's version to `0.0.1` would fix this. Would that be possible?

Thanks,
Mat

**Comment by KasperAndersson** [comment]
@mbaxter91288 Did you try to install https://www.npmjs.com/package/gutenberg ?

I got this trying install ''gutenberg-web-type", so I wondering if this is even published to NPM?

```gutenberg-web-type' is not in the npm registry.```

**Comment by dkerzig** [comment]
+1 for updating version number in `package.json` and publish the thing to NPM

**Comment by matejlatin** [comment]
Hey guys, I haven't published it to NPM yet. Will try to do it this weekend. @KasperAndersson that Gutenberg is something else :)

**Comment by KasperAndersson** [comment]
@matejlatin That was my point - so this issue is invalid, because it's not this package. Looking forward to see this as a NPM.

**Comment by KasperAndersson** [comment]
@matejlatin Starting a new internal project at the office, and we'll like to try your lib. What's the status on npm?

**Comment by matejlatin** [comment]
@KasperAndersson sorry, been very busy. I have a few pull requests to test and merge and then I'll publish it to npm. If all goes well it should be up tonight.

Looking forward to see what you do with it! :)

**Comment by matejlatin** [comment]
@KasperAndersson it's on NPM! Go ahead and run `npm install gutenberg-web-type`

**Comment by KasperAndersson** [comment]
Nice one! I'll try tmrw, thanks :+1:
