### ISSUE TITLE
GitHub's Releases feature

### ISSUE THREAD

**Issue by cjpatoilo** [matejlatin/Gutenberg#16]
Hi @matejlatin 

Today I saw some friends giving star in your project. So I decided to look closely. I was surprised at the quality of the project, the way you approached the problem and mainly the technical quality. Amazing job! The homepage is beautiful. Congrats dude.

So, you could use [GitHub Releases feature for its changelogs](https://github.com/blog/1547-release-your-software). As an example see the Releases section of our GitHub project, [Milligram](https://github.com/milligram/milligram/releases).

About versioning, you could use the [semantic versioning](http://semver.org/). This can solve this issue #15 

Cheers

**Comment by matejlatin** [comment]
Hey @cjpatoilo thanks. Let me take a look at this.

**Comment by matejlatin** [comment]
@cjpatoilo should the releases be named v1.1.0 or just 1.1.0?

**Comment by geoffdavis92** [comment]
@matejlatin For your site/README, it's up to you, but files like [`package.json`](https://github.com/milligram/milligram/blob/v1.1.0/package.json) or [`bower.json`](https://github.com/milligram/milligram/blob/v1.1.0/bower.json) use "1.1.0", which does not use the "v". (checkout line 3 on each file)

For more info on semver, check out [http://semver.org/](http://semver.org/).

Speaking of package/bower JSON files, you should add this to npm and/or bower :)

**Comment by cjpatoilo** [comment]
Hi @matejlatin I am going through major changes: new company, new challenges, university, studies.. all this has consumed my time.

So, about versioning I usually use with `v` before but you can use any option to set the tag (version). See this example with `v` on tag: https://github.com/facebook/react/blob/v0.14.1/package.json

**Comment by matejlatin** [comment]
@geoffdavis92 @cjpatoilo thanks for your help guys. I used versioning with 'v' on GitHub releases but in the package.json it's only '1.1.0'. Now also on npm, so you can install with `npm install gutenberg-web-type`
