### ISSUE TITLE
Translations to stylus

### ISSUE THREAD

**Issue by leny** [matejlatin/Gutenberg#19]
Hi, 

I'm very interested by your project and will be happy to translate it into Stylus, which I use more than sass.

How would you like to do ?

A separate repo (Gutenberg-stylus), or forking this one and add .styl files asides of the .sass ones ?

Regards,

**Comment by marcobiedermann** [comment]
How about switching to normal CSS with CSS Variables using [PostCSS](https://github.com/postcss/postcss) with [CSSNext](http://cssnext.io/)?
This way, it is independent of any proprocessors.

**Comment by leny** [comment]
Why not both?  
So anyone can be happy :)

**Comment by matejlatin** [comment]
Hey @leny ! @luclemo has already started working on translating it to Stylus. Maybe the two of you could collaborate on this?

@marcobiedermann I haven't had a chance to dive into PostCSS and CSSNext and I don't think I'll have time in the future. This whole project started partly because I wanted to learn Sass. I guess it could be done. Something I really like about Sass are the mixins, which make the code cleaner and easier to understand...

**Comment by marcobiedermann** [comment]
@matejlatin Setting up PostCSS is very easy. I could help you with that if you like to.
In my opinion, you do not really need Sass and mixins (see #23).
The huge benefit of PostCSS would be that you do not need any third-party software to use your source code in production. Chrome Canary and iOS do support [CSS Variables](http://caniuse.com/#feat=css-variables) yet. So you could use the "future syntax" in modern browsers now and provide a fallback via CSSNext for older ones.

**Comment by luclemo** [comment]
Hey @leny I was thinking of just adding the stylus directory as you suggested, but would love a hand with this. I feel comfortable doing the SCSS => Stylus translation, but I'm not familiar with grunt at all (more familiar with gulp). Also, while I use git on my own a lot, this would be my first open-source contribution so the whole workflow is a bit shaky for me.

**Comment by marcobiedermann** [comment]
@luclemo Adding a grunt stylus task is not that difficult:

Git workflow:
1.  Fork this repo
2. Clone your fork to you remove machine via `git clone GIT_URL`
3. Create a new branch via `git branch feature/stylus`
4. Checkout you new branch via `git checkout feature/stylus`
5. Make your changes
6. Add all your changes to the staging area via `git add .`
7. Commit your staging files via `git commit -m "COMMIT MESSAGE HERE"`
8. Push your local changes to your fork via `git push origin feature/stylus`
9. Create pull request on GitHub

If you like to, you could check out this free course on [egghead.io](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github)

Adding Stylus:

Add grunt-contrib-stylus package:
```
npm install grunt-contrib-stylus --save-dev
```

Add stylus task
```
stylus: {
  dist: {
    options: {
    },
    files: [{
      expand: true,
      cwd: 'src/styles/stylus',
      src: ['**/*.styl'],
      dest: 'src/styles',
      ext: '.css'
    }]
  }
}

grunt.loadNpmTasks('grunt-contrib-stylus');
```

The problem will be that both stylus and sass will create a css output file which might resole in some merge conflicts.

**Comment by leny** [comment]
Hi @luclemo , don't hesitate to push your work and I'll review it if it needs.
And congrats for your first contribution... the first of many to come! ;)

**Comment by luclemo** [comment]
@marcobiedermann thanks for the super clear steps! I should be able to handle that :)
@leny will do!
Thanks guys :)

**Comment by matejlatin** [comment]
Thanks for contributing guys! @marcobiedermann shouldn't the Sass step be removed from the gruntfile.js on the Stylus branch?

**Comment by marcobiedermann** [comment]
@matejlatin 
Yes, that's the problem I mentioned earlier

> The problem will be that both stylus and sass will create a css output file which might resole in some merge conflicts.

**Comment by luclemo** [comment]
Hey guys, it's going well but I've hit a snag translating these two blocks.
```
// Modular Scale
$modular-scale: (
  xxxl: 4.3,
  xxl: 3.5,
  xl: 3,
  l: 2.5,
  m: 2,
  s: 1.6875,
  xs: 1.4375,
  xxs: 1.2,
  xxxs: 1,
  xxxxs: .8125
) !default;

// Headings Options
// [ h1: size (in rem), line height (* leading), margin top (* leading), margin bottom (* leading) ]
$headings: (
  h1: (2.5, 2, 4, 1),
  h2: (1.6875, 1.5, 2.5, .5),
  h3: (1.375, 1, 2, .5),
  h4: (1.2, 1, 1.5, .5),
  h5: (1, 1, 2.5, .5),
  h6: (1, 1, 2.5, .5)
) !default;
```
I've tried this format:
```
$headings = (
h1: (2.5, 2, 4, 1),
h2: (1.6875, 1.5, 2.5, 0.5),
h3: (1.375, 1, 2, 0.5),
h4: (1.2, 1, 1.5, 0.5),
h5: (1, 1, 2.5, 0.5),
h6: (1, 1, 2.5, 0.5)
)
```
As well as this
```
$headings = (
h1: (2.5, 2, 4, 1)
h2: (1.6875, 1.5, 2.5, 0.5)
h3: (1.375, 1, 2, 0.5)
h4: (1.2, 1, 1.5, 0.5)
h5: (1, 1, 2.5, 0.5)
h6: (1, 1, 2.5, 0.5)
)
```
Even this
```
$headings = (h1: (2.5, 2, 4, 1), h2: (1.6875, 1.5, 2.5, 0.5), h3: (1.375, 1, 2, 0.5), h4: (1.2, 1, 1.5, 0.5), h5: (1, 1, 2.5, 0.5), h6: (1, 1, 2.5, 0.5))
```
But keep getting syntax errors when it tries to compile and I'm not getting anything from the docs.

**Comment by leny** [comment]
Hi,

I'll take a look maybe tomorrow, probably this week-end.

**Comment by luclemo** [comment]
Hi @leny don't worry about this, I got it resolved and moving onto the next files. :)

**Comment by matejlatin** [comment]
I decided to keep this project Sass-only for now. I'm flirting with the suggestion by @marcobiedermann to rewrite it independently from preprocessors in the future. Closing this issue.
