### ISSUE TITLE
Remove rem to px mixins

### ISSUE THREAD

**Issue by marcobiedermann** [matejlatin/Gutenberg#23]
I suggest removing all mixins which provide a fallback for `rem` units.
I would use a tool like [CSSNext](http://cssnext.io/features/#rem-unit-px-fallback) with [PostCSS](https://github.com/postcss/postcss) or [grunt-rem-to-px](https://www.npmjs.com/package/grunt-rem-to-px)

**Comment by matejlatin** [comment]
The mixins don't convert `rem` to `px`. They write css in both, `px` as fallback and `rem` as ideal.

**Comment by marcobiedermann** [comment]
Sorry, my bad. Yes I mean exactly that. This cask could be accomplished with the tools, see above

**Comment by matejlatin** [comment]
Will probably be a part of the tool in some later version (v2?). Closing the issue.
