### ISSUE TITLE
Help to customize and generate CSS

### ISSUE THREAD

**Issue by schollz** [matejlatin/Gutenberg#32]
Hi, this is a great tool! I'm having trouble getting started with customization. I'm not familiar with Grunt/Gulp. I understand CSS and I know how to customize the .scss, but what do I do to compile these into the .css files? I'd appreciate any help!

**Comment by connor-baer** [comment]
I think gulp is easier than grunt, but that's a matter of preference. To learn gulp, have a look at these two articles: https://markgoodyear.com/2014/01/getting-started-with-gulp/, https://travismaynard.com/writing/getting-started-with-gulp

**Comment by schollz** [comment]
Ok thanks, that helped a lot!

**Comment by connor-baer** [comment]
@schollz Glad I could help!
