### ISSUE TITLE
Single directions margins maybe?

### ISSUE THREAD

**Issue by Madebym** [matejlatin/Gutenberg#33]
I see that Gutenberg uses double direction margins. Have you maybe thought about using single direction margins?

It is explained nicely here http://csswizardry.com/2012/06/single-direction-margin-declarations/

These typographic projects favor this approach, maybe some others too, but I only know about these.

http://typeplate.com/
http://typesettings.io/
https://github.com/zellwk/typi
https://sassline.com/

Maybe I am missing something, but I see you have top and bottom margins set for your headings. I am no expert on this, far from that :)

**Comment by matejlatin** [comment]
Hey @Madebym , I remember that article :)

What I hate about this solution is that by doing so, headings get stuck right in the middle of the space between paragraphs. I prefer heading to be closer to the paragraph to which they're headings to (smaller margin at the bottom, larger on top). So besides keeping a vertical rhythm this also establishes a nice visual hierarchy. 

You could still set top margins to 0 for all headings in Gutenberg but I think the single direction margins is more a personal preference than a rule :)
