### ISSUE TITLE
Font defaults from html to *

### ISSUE THREAD

**Issue by ricardozea** [matejlatin/Gutenberg#36]
Hey @matejlatin I ran into a small situation, not an issue per se.

I noticed that my `<button>` wasn't taking the font family (Merriweather in my case), it was using Arial. Actually, now that I remember, the `input` fields were suffering the same issue.

I saw that in the `_gutenberg-typography.scss` partial the `// Font defaults` section is targeting the `html` like so:

    html {
      font-size: #{$base + 'px'};
      font-size: #{$base-font-size + '%'};
      font-family: $font-body;
      color: $color-font-body;
    }

Now, since I want **every single** element in my design to use the same typeface, I changed the above selector to the one we use when declaring `box-sizing: border-box`:

    *, *:before, *:after {
      font-size: #{$base + 'px'};
      font-size: #{$base-font-size + '%'};
      font-family: $font-body;
      color: $color-font-body;
    }

Now, this may very well be my personal case, but from a design standpoint using the same typeface across a design is pretty much rule #A1 of typography. Any additional typefaces can be introduced after the main typeface has been defined.

Just a thought if you want to incorporate it in the project.

Gutenberg is working like a charm so far :)

Thanks.

**Comment by matejlatin** [comment]
Thanks for the comment @ricardozea . Will definitely consider this for future updates.
