### ISSUE TITLE
images squashed when resizing the window

### ISSUE THREAD

**Issue by GeorgeStrakhov** [matejlatin/Gutenberg#40]
Suggest to add a debounced onresize hook to recalculate image sizes.

**Comment by matejlatin** [comment]
@GeorgeStrakhov yup I'm aware of this problem. Thanks for the suggestion. What do you mean by "debounced"?

**Comment by GeorgeStrakhov** [comment]
Sure. https://lodash.com/docs#debounce
This is just a performance-optimising measure - to make sure that browser
doesn't go crazy trying to run your resize function 60 times per second
while the window is being resized.

**Comment by matejlatin** [comment]
Awesome, we should definitely do it. Thanks @GeorgeStrakhov

**Comment by GeorgeStrakhov** [comment]
No problem. A bit busy today, but can handle this and do a PR tomorrow.

**Comment by GeorgeStrakhov** [comment]
Sorry for late. Here you go: https://github.com/matejlatin/Gutenberg/pull/42

**Comment by matejlatin** [comment]
@GeorgeStrakhov thanks.
