### ISSUE TITLE
Mixins are not imported

### ISSUE THREAD

**Issue by gregoralbrecht** [matejlatin/Gutenberg#44]
I just included the scss files in a project for the first time and noticed that you don't import `gutenberg-mixins.scss` inside `gutenberg.scss` although you use it there. This throws an error for me, because `@include line-height()` is not defined.

If you just want to include it, I can open a PR if you want. Just let me know.

_Really nice work by the way!_

**Comment by matejlatin** [comment]
Hey @gregoralbrecht thanks! Hm, the gutenberg-mixins gets imported in gutenberg-typography. I find it strange that you get an error. Nobody reported it so far...
