### ISSUE TITLE
3rd party grid recommendations

### ISSUE THREAD

**Issue by ghost** [matejlatin/Gutenberg#47]
Hello,

I would like to ask for a recommendation of a 3rd party grid system that can be easily combined with Gutenberg.

The kit is already pretty much a complete framework for a blog that I am making, but I also would like to add logo with navigation and a two-column footer to a site, and thus need an additional component (as someone not well versed in CSS in order to add a compatible grid myself).

Thank you!

**Comment by matejlatin** [comment]
Hey @keenam I can't really give you an advice on that but I was thinking of transforming Gutenberg into a proper framework some time in the future. I know a lot of people have been asking if it works with Bootstrap but I don't know if they tried. I think it could, but probably not very easy to set up...

**Comment by keenam** [comment]
Thank you @matejlatin , that would be a great enhancement to Gutenberg. As I mentioned, it is already almost a complete framework for my current purpose.

I'll look into the project below, which uses Gutenberg and LostGrid at its base, to see what can I do about this issue meanwhile:

https://github.com/wpioneer/gatsby-starter-lumen

**Comment by matejlatin** [comment]
@keenam, awesome! Hm, I didn't know about the Lumen project. Looks pretty cool. How did you find it?

**Comment by keenam** [comment]
I think that might've found a suitable grid - [Dead Simple Grid](https://github.com/mourner/dead-simple-grid). And that's the whole framework below!

```
/* Dead Simple Grid (c) 2015 Vladimir Agafonkin */

.row .row { margin:  0 -1.5em; }
.col      { padding: 0  1.5em; }

.row:after {
    content: "";
    clear: both;
    display: table;
}

@media only screen { .col {
    float: left;
    width: 100%;
    box-sizing: border-box;
}}
```
DEMO:
http://mourner.github.io/dead-simple-grid/

**Comment by matejlatin** [comment]
Looks interesting.. Will take a look.

**Comment by keenam** [comment]
In the end, for an easier grid setup I went with the declarative [Flexgrid.css](https://github.com/axiomzen/flexgrid.css) system.

**Comment by matejlatin** [comment]
Interesting, @keenam . Will take a look once we start taking this project further. Thanks.

**Comment by matejlatin** [comment]
note to self: https://gridder.io/

**Comment by cherylcarpenter** [comment]
i searched high and low for a responsive typography starter scss file. got this all set up and then discovered that it overides bootstrap width. Seems a bit crazy. And seems should have been spelled out very early on that this invents its own grid.

**Comment by matejlatin** [comment]
@cherylcarpenter I know about that 😢 I'm planning on making this framework a bit more liberal in the future so it would play nicely with Bootstrap etc.
