### ISSUE TITLE
no second-order grid

### ISSUE THREAD

**Issue by maxinakenty** [matejlatin/Gutenberg#61]
Hello, Matej! Thank you for your beautiful library. Faced with a problem when setting the horizontal rhythm. No second row of the grid.
Your demo http://joxi.ru/nAyqJWqUX8wMXA
My page http://joxi.ru/J2b1BO1C4jVOlm

Examining the code, I noticed the following changes.
Your demo http://joxi.ru/bmoWJMWSMayvEm
My page http://joxi.ru/D2PDdMDsdQJzo2

I downloaded GUTENBERG of npm. If this information is something can help.

Mac OS X Google Chrome 54.0.2840.71 (64-bit)

**Comment by matejlatin** [comment]
Hey @maxinakenty I noticed this at some point and came to a conclusion that it happens on some screens. Mostly lower resolution screens. Are your screenshots taken all on the same screen?

The npm version is the same as on Github.

**Comment by maxinakenty** [comment]
@matejlatin, screenshots made on the same screen. I macBook air 13. This is probably the only Google Chrome problem. Since it is not in other browsers.

I would be very grateful if you would refer to the documentation, how you carded line-height and other values. Or maybe, if you is not difficult, you could share useful information and send me an email link? I also did not find any where in the source code where you use a Modular Scale. Thank you in advance.

**Comment by matejlatin** [comment]
@maxinakenty did you find the reason for this problem perhaps? I haven't had time to look into it...

What do you mean by how I "carded" line-height? The modular scale is currently set manually but I'm looking to come up with a better solution in the future.

**Comment by maxinakenty** [comment]
`.grid,
.grid-double {
  background-image: linear-gradient(to bottom,rgba(0,170,255,.3) 1px,transparent 1px);
  background-repeat: repeat;
  background-position: left top;
  background-size: 100% 16px;

  @include up(md) {
    background-size: 100% 32px;
  }
}

.grid-double {
  background-image: linear-gradient(to bottom,rgba(0,170,255,.3) 1px,transparent 1px,transparent 13px,rgba(0,170,255,.2) 13px,transparent 14px,transparent 26px);

  @include up(md) {
    background-image: linear-gradient(to bottom,rgba(0,170,255,.3) 1px,transparent 1px,transparent 16px,rgba(0,170,255,.2) 16px,transparent 17px,transparent 32px);
  }
}`

**Comment by maxinakenty** [comment]
Hi, @matejlatin! I managed to fix the bug in double-grid. Just exclude rem from the parameters in the grid and double-grid classes. Then the grid is correctly displayed in all modern browsers. I have not tested it in IE.

**Comment by maxinakenty** [comment]
.grid,
.grid-double {
  background: linear-gradient(to bottom, hsla(200, 100%, 50%, .3) 1px,transparent 1px) repeat left top;
  background-size: 100% 26px;

  @include up(md) {
    background-size: 100% 32px;
  }
}

.grid-double {
  background-image: linear-gradient(to bottom, hsla(200, 100%, 50%, .3) 1px,transparent 1px,transparent 13px, hsla(200, 100%, 50%, .2) 13px,transparent 14px,transparent 26px);

  @include up(md) {
    background-image: linear-gradient(to bottom, hsla(200, 100%, 50%, .3) 1px,transparent 1px,transparent 16px, hsla(200, 100%, 50%, .2) 16px,transparent 17px,transparent 32px);
  }
}

**Comment by matejlatin** [comment]
@maxinakenty thanks for taking the time to look into this. I'll check this asap. I guess IE really isn't a modern browser anymore :D
