### ISSUE TITLE
Override variables in horizontal-rule.scss

### ISSUE THREAD

**Issue by lunaryorn** [matejlatin/Gutenberg#62]
I tried to override variables in `horizontal-rule.scss` but failed because unlike the ones in `gutenberg-config.scss` their values aren't marked `!default`.

Shouldn't the variables in `horizontal-rule.scss` be `!default` as well?  Or am I supposed to edit the file directly to change the appearance of horizontal rules?

**Comment by matejlatin** [comment]
Hey @lunaryorn you're right. Will update this in the next release. Cheers.
