### ISSUE TITLE
Remove external font dependencies

### ISSUE THREAD

**Issue by JacobDB** [matejlatin/Gutenberg#79]
I'd appreciate it if the external font dependencies could be removed, as they're adding an extra HTTP request that apparently can't be overridden. I'd recommend continuing to use the font names in the stylesheets, but instead of including the Google Fonts stylesheets in the CSS, instead include instructions on how to include the recommended fonts in the documentation.

https://github.com/matejlatin/Gutenberg/blob/master/src/style/_gutenberg-config.scss#L60-L87

**Comment by JacobDB** [comment]
Ah, never mind, I didn't realize you could just override it with a couple of Sass variables. Still, I don't think these should be baked in the the stylesheet, but overriding the variables will do for my purposes.

```scss
$theme: custom;
$font-body: "Open Sans", sans-serif;

@import "gutenberg-web-type/src/style/gutenberg.scss";
```

**Comment by matejlatin** [comment]
@JacobDB I'm glad you found a solution! 👍 

Thanks for the suggestion. I'll keep it in mind for any potential future updates.
